---
- name: Make temp dir
  file:
    path: "{{ flux_tmp_dir }}"
    state: directory


- name: Create flux ssh secret
  shell: "kubectl --context {{ context }} \
  create secret generic flux-git-deploy -n {{ flux_name_space }} \
  --from-file=identity={{ flux_tmp_dir }}/id_rsa --dry-run -o json |  \
  kubectl --context {{ context }} apply -f -"


- name: Create flux-account.yaml
  template:
    src: flux-account.yaml.j2
    dest: "{{ flux_tmp_dir }}/flux-account.yaml"

- name: Create flux account
  shell: "{{ kubectl_cmd }} apply --context {{ context }} -f {{ flux_tmp_dir }}/flux-account.yaml"


- name: Create flux-deployment.yaml
  template:
    src: flux-deployment.yaml.j2
    dest: "{{ flux_tmp_dir }}/flux-deployment.yaml"

- name: Create flux deployment
  shell: "{{ kubectl_cmd }} apply --context {{ context }} -f {{ flux_tmp_dir }}/flux-deployment.yaml"

- name: Create flux-service.yaml
  template:
    src: flux-service.yaml.j2
    dest: "{{ flux_tmp_dir }}/flux-service.yaml"

- name: Create Flux Serivce
  shell: "{{ kubectl_cmd }} apply --context {{ context }} -f {{ flux_tmp_dir }}/flux-service.yaml"

- name: Create memchache-dep.yaml
  template:
    src: memcache-dep.yaml.j2
    dest: "{{ flux_tmp_dir }}/memcache-dep.yaml"

- name: Create memcache deployment
  shell: "{{ kubectl_cmd }} apply --context {{ context }} -f {{ flux_tmp_dir }}/memcache-dep.yaml"


- name: Create memchache-svc.yaml
  template:
    src: memcache-svc.yaml.j2
    dest: "{{ flux_tmp_dir }}/memcache-svc.yaml"

- name: Create memcache service
  shell: "{{ kubectl_cmd }} apply --context {{ context }} -f {{ flux_tmp_dir }}/memcache-svc.yaml"


- name: Delete tmp ansible folder
  file:
    path: "{{ flux_tmp_dir }}"
    state: absent

...