---
# Source: prometheus-operator/templates/exporters/kube-etcd/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: prometheus-prometheus-oper-kube-etcd
  labels:
    app: prometheus-operator-kube-etcd
    jobLabel: kube-etcd
    
    chart: prometheus-operator-4.3.2
    release: "prometheus"
    heritage: "Tiller"
    clusterName: ismail.oteemo-xc.com
    
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 4001
      protocol: TCP
      targetPort: 4001
  selector:
      
    k8s-app: etcd-server
  type: ClusterIP