---
# Source: prometheus-operator/charts/grafana/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-grafana-clusterrolebinding
  labels:
    app: grafana
    chart: grafana-2.2.0
    release: prometheus
    heritage: Tiller
subjects:
  - kind: ServiceAccount
    name: prometheus-grafana
    namespace: design1
roleRef:
  kind: ClusterRole
  name: prometheus-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io