---
# Source: prometheus-operator/charts/grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: prometheus-grafana
  #Modified from upstream chart explicitly adding namespace
  namespace: design1
  labels:
    app: grafana
    chart: grafana-2.2.0
    release: prometheus
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "YWRtaW4xMjM="
  ldap-toml: ""
