---
# Source: prometheus-operator/charts/kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-state-metrics
    chart: kube-state-metrics-0.14.1
    heritage: Tiller
    release: prometheus
  name: prometheus-kube-state-metrics
  #Modified from upstream chart explicitly adding namespace
  namespace: design2