---
# Source: prometheus-operator/charts/kube-state-metrics/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-state-metrics
  #Modified from upstream chart explicitly adding namespace
  namespace: design2
  labels:
    app: kube-state-metrics
    chart: "kube-state-metrics-0.14.1"
    release: "prometheus"
    heritage: "Tiller"
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: "ClusterIP"
  ports:
  - name: "http"
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: kube-state-metrics
    release: prometheus
