---
# Source: prometheus-operator/templates/alertmanager/psp-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-prometheus-oper-alertmanager
  #Modified from upstream chart explicitly adding namespace
  namespace: design2
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-4.3.2
    release: "prometheus"
    heritage: "Tiller"
    clusterName: ismail.oteemo-xc.com
    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-prometheus-oper-alertmanager
subjects:
  - kind: ServiceAccount
    name: prometheus-prometheus-oper-alertmanager
    namespace: design2
