---
# Source: prometheus-operator/templates/prometheus-operator/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-prometheus-oper-operator
  #Modified from upstream chart explicitly adding namespace
  namespace: design2
  labels:
    app: prometheus-operator-operator
    
    chart: prometheus-operator-4.3.2
    release: "prometheus"
    heritage: "Tiller"
    clusterName: ismail.oteemo-xc.com
    
spec:
  endpoints:
  - port: http
    honorLabels: true
  selector:
    matchLabels:
      app: prometheus-operator-operator
      release: "prometheus"
  namespaceSelector:
    matchNames:
      - "design2"