{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "kube-state-metrics.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kube-state-metrics.fullname" . }}
  #Modified from upstream chart explicitly adding namespace
  namespace: {{ .Release.Namespace }}
{{- end -}}
