{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "grafana.serviceAccountName" . }}
  #Modified from upstream chart explicitly adding namespace
  namespace: {{ .Release.Namespace }}
{{- end }}
