---
# Source: prometheus-operator/templates/prometheus/rolebinding-config.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-prometheus-oper-prometheus-config
  #Modified from upstream chart explicitly adding namespace
  namespace: design1
  labels:
    app: prometheus-operator-prometheus
    
    chart: prometheus-operator-4.3.2
    release: "prometheus"
    heritage: "Tiller"
    clusterName: ismail.oteemo-xc.com
    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-prometheus-oper-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-prometheus-oper-prometheus
  namespace: design1
