---
# Source: prometheus-operator/templates/prometheus/role-specificNamespace.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleList
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-prometheus-oper-prometheus
    labels:
      app: prometheus-operator-prometheus
      
      chart: prometheus-operator-4.3.2
      release: "prometheus"
      heritage: "Tiller"
      clusterName: ismail.oteemo-xc.com
      
    namespace: "kube-system"
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-prometheus-oper-prometheus
    labels:
      app: prometheus-operator-prometheus
      
      chart: prometheus-operator-4.3.2
      release: "prometheus"
      heritage: "Tiller"
      clusterName: ismail.oteemo-xc.com
      
    namespace: "design1"
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch